steps:
  # Install dependencies and build the project
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west9-docker.pkg.dev/gkemedium/ethindex/my-cloud-run-image', '.']
    env:
      - 'REGION=europe-west9'

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west9-docker.pkg.dev/gkemedium/ethindex/my-cloud-run-image']
    env:
      - 'REGION=europe-west9'

  # Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-cloud-run-service'
      - '--image=europe-west9-docker.pkg.dev/gkemedium/ethindex/my-cloud-run-image'
      - '--platform=managed'
      - '--region=europe-west9'
      - '--allow-unauthenticated'